site_name: "BBTR"
site_url: !ENV [CANONICAL_URL, CF_PAGES_URL, "https://bbtr.fr/"]
site_description: "Organisez d'excellents tournois Magic: the Gathering"
# site_author:
theme:
  language: fr
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  # If we add cookies, here's how to deal with cookie consent
  # https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/
  features:
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - toc.follow
  palette:

    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Passer au mode clair

    - scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Passer au mode sombre

nav:
  - Accueil: 'index.md'
  - Philosophie: 'philosophie.md'
  - Préparation:
    - Préparation: 'preparation/index.md'
    - Trouver une salle: 'preparation/salle.md'
    - Former son équipe: 'preparation/equipe.md'
    - Construire une table de lots: 'preparation/lots.md'
    - Arbitres: 'preparation/arbitres.md'
    - Prendre les inscriptions: 'preparation/inscriptions.md'
    - Communication: 'preparation/communication.md'
    - Extras:
      - Goodies: 'preparation/goodies.md'
      - Shop: 'preparation/shop.md'
      # - Artistes: 'preparation/artistes.md'
      - Stream: 'preparation/stream.md'
  - Communication:
    - Communication: 'communication/index.md'
    - Communauté locale: 'communication/communaute.md'
    - Partenaires: 'communication/partenaires.md'
    - Réseaux sociaux: 'communication/reseaux.md'
    - Vie privée et RGPD: 'communication/rgpd.md'
  - Jour J: 'jourj/index.md'
  - Outils: 'outils/index.md'

plugins:
  - search
  - social

# extra:
#   social:
#     - icon: fontawesome/brands/discord
#       link: https://discord.gg/foobar
#       name: "Rejoignez-nous sur Discord"

  # If we setup this, add cookie consent
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX

copyright: Copyright &copy; 2023 - BBTR team

# https://squidfunk.github.io/mkdocs-material/setup/extensions/
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-a-glossary
